name: My first CI pipeline
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Set up go
        uses: action/checkout@v2
        with:
          go-version: '^1.18'

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Lint code
        run:  |
          go install golang.org/x/lint/golint@latest
          golint ./...  
        