name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22.2]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Go for the backend
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    # Install backend dependencies
    - name: Install backend dependencies
      run: |
        go mod tidy
        go build -v ./...
        go test -v ./...

    # Lint Go code
    - name: Lint Go code
      run: |
        go install golang.org/x/lint/golint@latest
        golint ./...

    # List directories for verification
    - name: List frontend directory
      run: |
        cd frontend
        ls -la

    - name: List backend directory
      run: |
        ls -la
